# Generated by Django 2.0.4 on 2018-05-05 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('co2_concentration', models.DecimalField(decimal_places=1, max_digits=5)),
                ('temp', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=7)),
                ('station', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='co2data',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.Location'),
        ),
    ]
