# Generated by Django 2.0.4 on 2018-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('co2_concentration', models.DecimalField(decimal_places=1, max_digits=5)),
                ('temp', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
